/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 15:49:02 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import main.Account;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update(36500);
      assertTrue(boolean0);
      
      boolean boolean1 = account0.credit(36500);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-5000));
      boolean boolean1 = account0.undoUpdate(0);
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update(36500);
      assertTrue(boolean0);
      
      int int0 = account0.calculateInterest();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Account account0 = new Account();
      account0.balance = (-6736);
      account0.balance = (-3289);
      account0.balance = (-36500);
      int int0 = account0.calculateInterest();
      assertEquals((-2), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.undoUpdate(3568);
      boolean boolean1 = account0.undoUpdate(3568);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.undoUpdate(3568);
      assertTrue(boolean0);
      
      boolean boolean1 = account0.update((-1307));
      boolean boolean2 = account0.update((-1307));
      assertFalse(boolean2 == boolean1);
      assertFalse(boolean2);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.credit((-1307));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.credit(3568);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Account account0 = new Account();
      int int0 = account0.calculateInterest();
      assertEquals(0, int0);
  }
}
