/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 15:49:12 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import main.Account;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Account account0 = new Account();
      account0.balance = (-5000);
      boolean boolean0 = account0.undoUpdate(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-5000));
      assertTrue(boolean0);
      
      boolean boolean1 = account0.undoUpdate(2611);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.undoUpdate(2810);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-3659));
      boolean boolean1 = account0.update((-3659));
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Account account0 = new Account();
      account0.lock();
      boolean boolean0 = account0.isLocked();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.isLocked();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Account account0 = new Account();
      account0.unLock();
  }
}
