/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 16:03:06 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import main.Account;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-5000));
      boolean boolean1 = account0.undoUpdate(0);
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-2895));
      assertTrue(boolean0);
      
      boolean boolean1 = account0.undoUpdate(4805);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.undoUpdate((-2895));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-2895));
      boolean boolean1 = account0.update((-2895));
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }
}
