/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 15:46:50 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import main.Account;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.credit(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Account account0 = new Account();
      account0.withdraw = (-941);
      account0.withdraw = (-1001);
      boolean boolean0 = account0.undoUpdate((-1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Account account0 = new Account();
      account0.balance = 0;
      account0.balance = 0;
      account0.balance = 0;
      account0.balance = 0;
      account0.balance = (-5000);
      boolean boolean0 = account0.undoUpdate(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-1000));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Account account0 = new Account();
      account0.balance = 0;
      account0.balance = 0;
      account0.balance = 0;
      account0.balance = 0;
      account0.balance = (-5000);
      boolean boolean0 = account0.update(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Account account0 = new Account();
      account0.withdraw = (-2326);
      boolean boolean0 = account0.undoUpdate((-1265));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update((-1097));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.credit((-1097));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.credit(21);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Account account0 = new Account();
      account0.balance = (-1097);
      account0.balance = (-1097);
      account0.balance = (-1097);
      account0.balance = (-5000);
      boolean boolean0 = account0.undoUpdate(11);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Account account0 = new Account();
      account0.balance = (-1097);
      account0.balance = (-1097);
      account0.balance = (-1097);
      boolean boolean0 = account0.undoUpdate((-1658));
      account0.balance = (-5000);
      boolean boolean1 = account0.update((-1658));
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.update(6416);
      assertTrue(boolean0);
  }
}
