/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 15:37:08 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import main.Application;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Application_ESTest extends Application_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Application application0 = new Application();
      application0.nextYear();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Application application0 = new Application();
      application0.nextDay();
  }
}
